### ISSUE TITLE
Curl option contains invalid characters (\0)

### ISSUE THREAD

**Issue by peterkomar** [guzzle/guzzle#1604]
Hello,
I use AWS SDK and I have an error time to time: Warning (2): curl_setopt_array(): Curl option contains invalid characters (\0) in [guzzlehttp/guzzle/src/Handler/CurlFactory.php, line 57] time to time

Restarting php-fpm temporary fix it.

nginx/1.6.2
PHP 5.6.24
guzzlehttp/psr7 1.3.1

**Comment by bitblower** [comment]
I've been getting this too today.

apache: 2.4.6
PHP: 5.6.21
guzzlehttp/guzzle 6.2.2

Fixed by restarting apache.

**Comment by sagikazarmark** [comment]
Without further context I am not sure there is much we can do here. Maybe you could try to file this issue in the AWS SDK repository.

The only thing that I can think of is that some kind of object is serialized and contains these null bytes unescaped which is not supported by cURL.

**Comment by EtienneRd** [comment]
Hello,

We've been having this issue as well, randomly, on our webservers. We narrowed it down to an opcache issue regarding CurlFactory.php file.

We didn't find how to reproduce the "opcache corruption" we suspect, however, what we did is isolate a server on which the issue was occurring and make requests that reproduce the problem. Then, I invalidated the CurlFactory.php file opcache using `opcache_invalidate('path/to/CurlFactory.php', true);`. This invalidation fixed the issue.

caddy: 0.9.5
PHP: 5.6.30
Zend Engine v2.6.0
with Zend OPcache v7.0.6-dev

guzzlehttp/guzzle: 6.2.3

**Comment by EtienneRd** [comment]
Hello again,

Just an update about our approach on this issue.

Knowing that it was the opcache of the CurlFactory file, I tried to disable progressively the optimizations Zend OpCache applies on the opcode to detect potential issues with some levels.
Sadly, even disabling every optimisation did not fix the issue.
So our temporary solution is to blacklist from opcache the file CurlFactory.

More information about the issue:
We observed that when this issue happened, the result of the curl call (which surprisingly was still done with the right params) was put in the STDOUT.
Apparently, this is the default value for the curl output, so this means that the option CURLOPT_FILE was not set due to a previous option containing \0. The side effect was that our requests making curl calls were outputting our internal apis' results to our requests' clients.

If you have any advice on how to further investigate this issue, or if you would like specific data to better understand the issue, don't hesitate to ask :)

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
