### ISSUE TITLE
docs: wrong base class for ConnectException

### ISSUE THREAD

**Issue by lazka** [guzzle/guzzle#2818]
The guzzle 7 upgrade guide states: 

> Class GuzzleHttp\Exception\ConnectException now extends GuzzleHttp\Exception\TransferException instead of GuzzleHttp\Exception\RequestException.

But the docs say ConnectException extends RequestException

https://docs.guzzlephp.org/en/stable/quickstart.html?highlight=transferexception#exceptions

**Comment by stemis** [comment]
This has already been resolved in the latest version: https://docs.guzzlephp.org/en/latest/quickstart.html?highlight=transferexception#exceptions

**Comment by lazka** [comment]
Thanks. It still states:

> A GuzzleHttp\Exception\ConnectException exception is thrown in the event of a networking error. This exception extends from GuzzleHttp\Exception\RequestException.

**Comment by stemis** [comment]
> Thanks. It still states:
> 
> > A GuzzleHttp\Exception\ConnectException exception is thrown in the event of a networking error. This exception extends from GuzzleHttp\Exception\RequestException.

Yes, I also spotted that, I created a PR in #2819 to solve this.

**Comment by johanrosenson** [comment]
When you visit [docs.guzzlephp.org](https://docs.guzzlephp.org/) you will be redirected to the `stable` documentation, but that still shows the wrong base class, but v7.0 use the new tree, should not the stable version of the docs show this? 

It threw me of for a while, and i thought the docs was out of date and was about to make a PR, but i see now that it's already fixed.

it's not obvious to me why the `stable` documentation is not up to date and not matching ^7.0, which i think is expected?

**Comment by Nyholm** [comment]
I think it will be updated at the next release.
